config/routes.rb
Rails.application.routes.draw do
  resources :user_matching_preferences
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  
  get '/about',     to: 'static_pages#about'
  get '/services',  to: 'static_pages#services'
  get '/pricing',   to: 'static_pages#pricing'
  
  #users
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @disable_header = true
  end

  def about
  end
  
  def pricing
  end
  
  def services
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="center"></div>


<div class="row-centered">
    <div class="col-md-2"></div>
    <div class="col-md-8 col-centered">
        <div class="padding-block">
        <div class="text-box-general">
            <h1 class="gold header-logo">
                Do you hate posting, writing captions, and responding to comments and messages? Don't worry, a lot of people do,
                and thats why we created SocialCurate.com! Social media is a necessary part of advertising in the modern world,
                but the truth is there are some people that just don't like spending that much time using it. That's why we're here.
                We create and curate socail media accounts for both business and personal use on a weekly basis. 
            </h1>
            <%= link_to '#' do %>
                <h1 class="gold header-logo">Sign Up!</h1>
            <% end %>
        </div>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    var textBox = document.querySelector('.text-box-general');
    
    setTimeout(function() {fadeInPartial(textBox)}, 500);
});
</script>

app/views/static_pages/home.html+phone.erb
<body class="mobile-home">
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>
<div class="center">
    
<div id="scene">
<div class="layer" data-depth="0.6"> 

    <div class="row">
        <h1 class="mobile-logo">Social Curate</h1>
    </div>

</div>
</div>
    
    &nbsp;
    <div class="row">
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box1">
                <h1 class="mobile-logo">Services</h1>
                <%= link_to services_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
        
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box2">
                <h1 class="mobile-logo">About</h1>
                <%= link_to about_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
   </div>
    &nbsp;
    
    <div class="row">
        <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box3">
                <h1 class="mobile-logo">Pricing</h1>
                <%= link_to pricing_path, class: 'gold', method: :get do %>
                    <button class="mobile-button">Click Here</button>
                <% end %>
            </div>    
        </div>
        
       <div class="col-xs-6">
            <div class="mobile-box" id="mobile-box4">
                <h1 class="mobile-logo">Contact</h1>
                <a href="mailto:christian.c.orourke@gmail.com?subject=Social%20Curate" target="_blank" class='gold'><button class="mobile-button">Send me an email!</button></a>
            </div>    
        </div>
    </div>
    &nbsp;
    <div class="row">
        
        <%= link_to signup_path, class: 'gold', method: :get do %>
            <button class="mobile-button-lg">Signup/Login</button>
        <% end %>
       
    </div>
    
</div>    
    
</body>

<script>
    // Initialize Parallax.js
      var scene = document.getElementById('scene');
      var parallax = new Parallax(scene);
</script>

app/views/static_pages/home.html.erb
<body id="home">


<div class="panels">
    
  <div class="panel panel2 secTransition">
    <p>About Info</p>
    <p class="main-header">About</p>
    <p>
      <%= link_to about_path, method: :get do %>
        <button>Click Here</button>
      <% end %>
    </p>
  </div>
    
  <div class="panel panel3 secTransition">
    <p></p>
    <p class="main-header">DnD Matchmaking</p>
    <p>
      <%= link_to signup_path, method: :get do %>
        <button>Signup/Login</button>
      <% end %>    
    </p>
  </div>
    
  <div class="panel panel5 secTransition">
    <p></p>
    <p class="main-header">Contact</p>
    <p><a href="mailto:christian.c.orourke@gmail.com?subject=Social%20Curate" target="_blank"><button>Send me an email!</button></a></p>
  </div>

</div>
</body>

<script>
document.addEventListener("DOMContentLoaded", function() {
  
  var p1 = document.querySelector('.panel1');
  var p2 = document.querySelector('.panel2');
  var p3 = document.querySelector('.panel3');
  var p4 = document.querySelector('.panel4');
  var p5 = document.querySelector('.panel5');


  const panels = document.querySelectorAll('.panel');
    
  function toggleOpen() {
    this.classList.toggle('open');
  }
    
  function toggleActive(event) {
    if (event.propertyName.includes('flex')) {
      this.classList.toggle('open-active');
    }
  }
    
  panels.forEach(panel => panel.addEventListener('click', toggleOpen));
  panels.forEach(panel => panel.addEventListener('transitionend', toggleActive));
    
  //fade in panels
  function fadeIn(ele) {
    ele.style.opacity = '1.0';
  }
  
  // remove longer transoition time
  function removeTransition(ele) {
    ele.classList.remove('secTransition');
  }

  setTimeout(function() {fadeIn(p3)}, 1000);
  setTimeout(function() {fadeIn(p2)}, 1700);
  setTimeout(function() {fadeIn(p5)}, 2400);

  // setTimeout(function() {fadeIn(p1)}, 1000);
  // setTimeout(function() {fadeIn(p2)}, 1700);
  // setTimeout(function() {fadeIn(p3)}, 2400);
  // setTimeout(function() {fadeIn(p4)}, 3100);
  // setTimeout(function() {fadeIn(p5)}, 3800);

  
  // remove longer transition time from all panels
  panels.forEach(panel => setTimeout(function() {removeTransition(panel)}, 3801));
});
</script>

app/views/static_pages/services.html.erb
<div id="preloader">
  <div id="status">&nbsp;</div>
</div>