config/routes.rb
Rails.application.routes.draw do
  resources :user_matching_preferences
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  
  get '/about',     to: 'static_pages#about'
  get '/services',  to: 'static_pages#services'
  get '/pricing',   to: 'static_pages#pricing'
  
  #users
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user_matching_preference.rb
class UserMatchingPreference < ApplicationRecord
    validates :user_id, presence: true
    validates :dm, inclusion: { in: [ true, false ] }
    validates :player, inclusion: { in: [ true, false ] }
    validates :play_style, presence: true
    validates :rule_style, presence: true
    validates :combat_level, presence: true
    validates :party_size, presence: true
    validates :campaign_duration, presence: true
    validates :campaign_frequency, presence: true
    validates :serious_level, presence: true
    validates :pvp, presence: true

    belongs_to :user,
        foreign_key: :user_id
end

app/controllers/user_matching_preferences_controller.rb
class UserMatchingPreferencesController < ApplicationController
  before_action :set_user_matching_preference, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user?, only: [:new, :show, :edit, :update, :destroy]
  before_action :correct_user_preference, only: [:edit, :update]

  def logged_in_user?
    unless logged_in?
      store_location
      flash[:danger] = "Please log in to continue"
      redirect_to login_url
    end
  end

  #dont want index of these
  # GET /user_matching_preferences
  # GET /user_matching_preferences.json
  # def index
  #   @user_matching_preferences = UserMatchingPreference.all
  # end

  # GET /user_matching_preferences/1
  # GET /user_matching_preferences/1.json
  def show
  end

  # GET /user_matching_preferences/new
  def new
    @user = current_user
    if @user.has_user_matching_preference?
      redirect_to @user.user_matching_preference
    else
      @user_matching_preference = UserMatchingPreference.new
    end
  end

  # GET /user_matching_preferences/1/edit
  def edit
    @user_matching_preference = UserMatchingPreference.find(params[:id])
  end

  # POST /user_matching_preferences
  # POST /user_matching_preferences.json
  def create
    @user_matching_preference = UserMatchingPreference.new(user_matching_preference_params)

    respond_to do |format|
      if @user_matching_preference.save
        format.html { redirect_to @user_matching_preference, notice: 'User matching preference was successfully created.' }
        format.json { render :show, status: :created, location: @user_matching_preference }
      else
        format.html { render :new }
        format.json { render json: @user_matching_preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_matching_preferences/1
  # PATCH/PUT /user_matching_preferences/1.json
  def update
    @user_matching_preference = UserMatchingPreference.find(params[:id])
    if @user_matching_preference.update_attributes(user_matching_preference_params)
      flash[:success] = "Preferences Updated!"
      redirect_to @user_matching_preference
    else
      render 'edit'
    end
  end

  # DELETE /user_matching_preferences/1
  # DELETE /user_matching_preferences/1.json
  def destroy
    @user_matching_preference.destroy
    respond_to do |format|
      format.html { redirect_to user_matching_preferences_url, notice: 'User matching preference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_matching_preference
      @user_matching_preference = UserMatchingPreference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_matching_preference_params
      #params.fetch(:user_matching_preference, {})     
      params.require(:user_matching_preference).permit(:user_id, :dm, :player, :play_style, :rule_style, :combat_level, :party_size, :campaign_duration, :campaign_frequency, :serious_level, :pvp)
    end

    def correct_user_preference
      @user = current_user
      @user_matching_preference = UserMatchingPreference.find(params[:id])
      redirect_to(root_url) unless @user.user_matching_preference == @user_matching_preference
    end
end

app/helpers/user_matching_preferences_helper.rb
module UserMatchingPreferencesHelper
end

app/views/user_matching_preferences/_form.html.erb
<%= form_with(model: user_matching_preference, local: true) do |form| %>
  <% if user_matching_preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_matching_preference.errors.count, "error") %> prohibited this user_matching_preference from being saved:</h2>

      <ul>
      <% user_matching_preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_matching_preferences/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user_matching_preference) do |f| %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.label "Dungeon Master" %>
      <%= f.check_box :dm, class: 'form-control' %>

      <%= f.label :player %>
      <%= f.check_box :player, class: 'form-control' %>

      <%= f.label :play_style %>
      <%= f.number_field :play_style, class: 'form-control' %>

      <%= f.label :rule_style %>
      <%= f.number_field :rule_style, class: 'form-control' %>

      <%= f.label :combat_level %>
      <%= f.number_field :combat_level, class: 'form-control' %>

      <%= f.label :party_size %>
      <%= f.number_field :party_size, class: 'form-control' %>

      <%= f.label :campaign_duration %>
      <%= f.number_field :campaign_duration, class: 'form-control' %>

      <%= f.label :campaign_frequency %>
      <%= f.number_field :campaign_frequency, class: 'form-control' %>

      <%= f.label :serious_level %>
      <%= f.number_field :serious_level, class: 'form-control' %>

      <%= f.label :pvp %>
      <%= f.number_field :pvp, class: 'form-control' %>

      <%= f.submit "Update Preferences", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/user_matching_preferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Matching Preferences</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_matching_preferences.each do |user_matching_preference| %>
      <tr>
        <td><%= link_to 'Show', user_matching_preference %></td>
        <td><%= link_to 'Edit', edit_user_matching_preference_path(user_matching_preference) %></td>
        <td><%= link_to 'Destroy', user_matching_preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Matching Preference', new_user_matching_preference_path %>

app/views/user_matching_preferences/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user_matching_preference) do |f| %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.label "Dungeon Master" %>
      <%= f.check_box :dm, class: 'form-control' %>

      <%= f.label :player %>
      <%= f.check_box :player, class: 'form-control' %>

      <%= f.label :play_style %>
      <%= f.number_field :play_style, class: 'form-control' %>

      <%= f.label :rule_style %>
      <%= f.number_field :rule_style, class: 'form-control' %>

      <%= f.label :combat_level %>
      <%= f.number_field :combat_level, class: 'form-control' %>

      <%= f.label :party_size %>
      <%= f.number_field :party_size, class: 'form-control' %>

      <%= f.label :campaign_duration %>
      <%= f.number_field :campaign_duration, class: 'form-control' %>

      <%= f.label :campaign_frequency %>
      <%= f.number_field :campaign_frequency, class: 'form-control' %>

      <%= f.label :serious_level %>
      <%= f.number_field :serious_level, class: 'form-control' %>

      <%= f.label :pvp %>
      <%= f.number_field :pvp, class: 'form-control' %>

      <%= f.submit "Save Preferences", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/user_matching_preferences/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_matching_preference_path(@user_matching_preference) %> |
<%= link_to 'Back', user_matching_preferences_path %>