config/routes.rb
Rails.application.routes.draw do
  resources :user_matching_preferences
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  
  get '/about',     to: 'static_pages#about'
  get '/services',  to: 'static_pages#services'
  get '/pricing',   to: 'static_pages#pricing'
  
  #users
  get '/signup',    to: 'users#new'
  post '/signup',   to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" id="header-button" data-toggle="collapse" data-target="#myNavbar">
        <%= image_tag('menu.png', size: '44x44') %>
      </button>
      
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <div class="center">
        <ul class="nav navbar-nav">
        
          <li><%= link_to "Home", root_path, method: :get, class: "header-logo" %></li>
          <li><%= link_to "About", about_path, method: :get, class: "header-logo" %></li>
          <li><%= link_to "Pricing", '#', class: "header-logo" %></li>
          
           <% if logged_in? %>
            <li><%= link_to "Users", users_path, class: "header-logo" %></li>
            <li><%= link_to 'Account', current_user, class: "header-logo" %></li>
            <li><%= link_to "Settings", edit_user_path(current_user), class: "header-logo" %></li>
            <li><%= link_to "Log out", logout_path, method: :delete, class: "header-logo" %></li>
          <% else %>
            <li><%= link_to "Log in", login_path, class: "header-logo" %></li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Moon|Half" />
  <meta property="og:description"   content="Web Development Blog" />
  <meta property="og:image"         content="assets/moonicon.png" />
  <meta property="og:image" content="#{image_url('preloader.gif')}" />
  
  <meta name="viewport" content="width=device-width; height=device-height; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
  <%= favicon_link_tag 'preloader.gif' %>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                'data-turbolinks-track': 'reload'%>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= render 'layouts/header' unless @disable_header %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
  </head>
  
  
    <body>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      
       <%= yield %>
    </body>
    
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    
    
    <script>
    
      
      /* Preloader */
      $(document).ready(function () {
        $(window).load(function(){
          $('#preloader').delay(400).fadeOut(500);
        })
      })
      
      /* AOS Init */
      AOS.init();
      
      function fadeInPartial(ele) {
        ele.style.opacity = '0.89';
      }
    </script>
    
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
    
</html>




<%# TODO: figure out what the buzzwords, locations, and democraphics should be %>